const noop = () => {};
export const $ = noop;
export const T = noop;
export const a = noop;
export const b = noop;
export const c = noop;
export const d = noop;
export const e = noop;
export const f = noop;
export const g = noop;
export const h = noop;
export const i = noop;
export const n = noop;
export const p = noop;
export const r = noop;
export const s = noop;